export const PRICE_TIERS = [
  { id: 'cheap', label: 'Barato', eb: 10 },
  { id: 'everyday', label: 'Cotidiano', eb: 20 },
  { id: 'costly', label: 'Oneroso', eb: 50 },
  { id: 'premium', label: 'Premium', eb: 100 },
  { id: 'expensive', label: 'Caro', eb: 500 },
  { id: 'very-expensive', label: 'Muito Caro', eb: 1000 },
  { id: 'luxury', label: 'Luxuoso', eb: 5000 },
  { id: 'super-luxury', label: 'Super Luxuoso', eb: 10000 },
];

export const CATEGORY_FILTERS = [
  { id: 'all', label: 'Todos' },
  { id: 'gear', label: 'Equipamento' },
  { id: 'fashion', label: 'Moda' },
  { id: 'melee', label: 'Armas Brancas' },
  { id: 'ranged', label: 'Armas Longo Alcance' },
  { id: 'exotic', label: 'Armas Exoticas' },
  { id: 'weapon-acc', label: 'Acessorios' },
  { id: 'ammo', label: 'Municao' },
  { id: 'armor', label: 'Armaduras' },
  { id: 'cyberware', label: 'Cyberware' },
  { id: 'drugs', label: 'Drogas' },
  { id: 'services', label: 'Servicos' },
  { id: 'housing', label: 'Habitacao' },
];

export const SOURCE_FILTERS = [
  { id: 'all', label: 'Qualquer origem' },
  { id: 'loja', label: 'Loja' },
  { id: 'clinica', label: 'Clinica' },
  { id: 'hospital', label: 'Hospital' },
  { id: 'mercado', label: 'Mercado Noturno' },
];

export const INVENTORY_CATEGORY_DEFAULTS = {
  gear: { w: 1, h: 1, color: '#4d80ff' },
  fashion: { w: 1, h: 1, color: '#ff87d4' },
  melee: { w: 1, h: 2, color: '#ff6b6b' },
  ranged: { w: 2, h: 1, color: '#ff3a3a' },
  exotic: { w: 2, h: 2, color: '#ff3a3a' },
  'weapon-acc': { w: 1, h: 1, color: '#78e2ff' },
  ammo: { w: 1, h: 1, color: '#7dc3ff' },
  armor: { w: 2, h: 2, color: '#ffe666' },
  drugs: { w: 1, h: 1, color: '#64f59d' },
};

export const NON_INVENTORY_CATEGORIES = ['services', 'housing', 'cyberware'];

export const SHOP_ITEMS = [
  {
    id: 'agent',
    name: 'Agente',
    category: 'gear',
    priceTier: 'premium',
    priceEb: 100,
    description: 'Smartphone com IA auto-adaptativa (+2 Pesquisa, +2 Guarda-roupa).',
  },
  {
    id: 'airhypo',
    name: 'Airhypo',
    category: 'gear',
    priceTier: 'costly',
    priceEb: 50,
    description: 'Injecao hipodermica de facil uso para dose unica.',
  },
  {
    id: 'anti-smog',
    name: 'Mascara Anti-Smog',
    category: 'gear',
    priceTier: 'everyday',
    priceEb: 20,
    grid: { w: 2, h: 1 },
    description: 'Filtra toxinas e fumaça do ar. Imune a gases inalatorios.',
  },
  {
    id: 'audio-recorder',
    name: 'Gravador de Audio',
    category: 'gear',
    priceTier: 'premium',
    priceEb: 100,
    description: 'Grava ate 24h em chip de memoria padrao.',
  },
  {
    id: 'binoculars',
    name: 'Binoculos',
    category: 'gear',
    priceTier: 'costly',
    priceEb: 50,
    grid: { w: 2, h: 1 },
    description: 'Ampliacao 2x ou 3x.',
  },
  {
    id: 'flashlight',
    name: 'Lanterna',
    category: 'gear',
    priceTier: 'everyday',
    priceEb: 20,
    description: 'Feixe de 100m/yds, ate 10h de uso.',
  },
  {
    id: 'food-stick',
    name: 'Barra de Comida',
    category: 'gear',
    priceTier: 'cheap',
    priceEb: 10,
    description: 'Barra de comida seca. Uma refeicao.',
  },
  {
    id: 'grapple-gun',
    name: 'Pistola de Gancho',
    category: 'gear',
    priceTier: 'premium',
    priceEb: 100,
    grid: { w: 2, h: 1 },
    description: 'Dispara gancho ate 30m/yds. Linha suporta 2x peso.',
  },
  {
    id: 'lockpicks',
    name: 'Kit de Arrombamento',
    category: 'gear',
    priceTier: 'everyday',
    priceEb: 20,
    grid: { w: 2, h: 1 },
    description: 'Ferramentas compactas para fechaduras mecanicas.',
  },
  {
    id: 'medscanner',
    name: 'Medscanner',
    category: 'gear',
    priceTier: 'very-expensive',
    priceEb: 1000,
    grid: { w: 2, h: 2 },
    description: '+2 Primeiros Socorros e Paramedico.',
  },
  {
    id: 'medtech-bag',
    name: 'Bolsa de Medtech',
    category: 'gear',
    priceTier: 'premium',
    priceEb: 100,
    grid: { w: 2, h: 2 },
    description: 'Kit medico completo para atendimentos rapidos.',
  },
  {
    id: 'radio-scanner',
    name: 'Radio Scanner',
    category: 'gear',
    priceTier: 'costly',
    priceEb: 50,
    grid: { w: 2, h: 1 },
    description: 'Escaneia bandas de radio e toca musicas.',
  },
  {
    id: 'knife',
    name: 'Faca de Combate',
    category: 'melee',
    priceTier: 'costly',
    priceEb: 50,
    description: 'Arma branca leve, dano 1d6.',
  },
  {
    id: 'machete',
    name: 'Facao',
    category: 'melee',
    priceTier: 'costly',
    priceEb: 50,
    grid: { w: 1, h: 3 },
    description: 'Arma branca media, dano 2d6.',
  },
  {
    id: 'crowbar',
    name: 'Pe de Cabra',
    category: 'melee',
    priceTier: 'costly',
    priceEb: 50,
    grid: { w: 1, h: 3 },
    description: 'Arma branca media, dano 2d6.',
  },
  {
    id: 'chainsaw',
    name: 'Motosserra',
    category: 'melee',
    priceTier: 'expensive',
    priceEb: 500,
    grid: { w: 2, h: 4 },
    description: 'Arma branca muito pesada, dano 4d6.',
  },
  {
    id: 'medium-pistol',
    name: 'Pistola Media',
    category: 'ranged',
    priceTier: 'costly',
    priceEb: 50,
    description: '2d6, carregador 12, ocultavel.',
  },
  {
    id: 'heavy-pistol',
    name: 'Pistola Pesada',
    category: 'ranged',
    priceTier: 'premium',
    priceEb: 100,
    description: '3d6, carregador 8, ocultavel.',
  },
  {
    id: 'smg',
    name: 'SMG',
    category: 'ranged',
    priceTier: 'premium',
    priceEb: 100,
    grid: { w: 2, h: 2 },
    description: '2d6, carregador 30, ocultavel.',
  },
  {
    id: 'shotgun',
    name: 'Espingarda',
    category: 'ranged',
    priceTier: 'expensive',
    priceEb: 500,
    grid: { w: 3, h: 1 },
    description: '5d6, carregador 4, 2 maos.',
  },
  {
    id: 'assault-rifle',
    name: 'Rifle de Assalto',
    category: 'ranged',
    priceTier: 'expensive',
    priceEb: 500,
    grid: { w: 3, h: 2 },
    description: '5d6, carregador 25, 2 maos.',
  },
  {
    id: 'grenade-launcher',
    name: 'Lancador de Granadas',
    category: 'ranged',
    priceTier: 'expensive',
    priceEb: 500,
    grid: { w: 3, h: 2 },
    description: '6d6, carregador 2, 2 maos.',
  },
  {
    id: 'malorian-3516',
    name: 'Malorian Arms 3516',
    category: 'exotic',
    priceTier: 'super-luxury',
    priceEb: 10000,
    grid: { w: 2, h: 1 },
    description: 'Pistola MP Exotica, dano 5d6, qualidade excelente.',
  },
  {
    id: 'mono-three',
    name: 'Kendachi Mono-Three',
    category: 'exotic',
    priceTier: 'luxury',
    priceEb: 5000,
    grid: { w: 2, h: 4 },
    description: 'Arma branca MP Exotica, 2 maos.',
  },
  {
    id: 'microwaver',
    name: 'Microwaver',
    category: 'exotic',
    priceTier: 'expensive',
    priceEb: 500,
    grid: { w: 2, h: 1 },
    description: 'Pistola MP Exotica, DV15 Cibertecnologia.',
  },
  {
    id: 'stun-baton',
    name: 'Bastao Atordoante',
    category: 'exotic',
    priceTier: 'premium',
    priceEb: 100,
    grid: { w: 1, h: 3 },
    description: 'Arma branca media, alvo fica inconsciente a 1 PV.',
  },
  {
    id: 'bayonet',
    name: 'Baioneta',
    category: 'weapon-acc',
    priceTier: 'premium',
    priceEb: 100,
    description: 'Acessorio para armas de ombro. Ocupa 1 slot.',
  },
  {
    id: 'drum-mag',
    name: 'Carregador Tambor',
    category: 'weapon-acc',
    priceTier: 'expensive',
    priceEb: 500,
    description: 'Aumenta capacidade. Impede ocultacao.',
  },
  {
    id: 'smartlink',
    name: 'Link de Arma Inteligente',
    category: 'weapon-acc',
    priceTier: 'expensive',
    priceEb: 500,
    description: '+1 em ataques a distancia. Ocupa 2 slots.',
  },
  {
    id: 'scope',
    name: 'Luneta de Mira Telescopica',
    category: 'weapon-acc',
    priceTier: 'premium',
    priceEb: 100,
    description: '+1 em tiros a longa distancia.',
  },
  {
    id: 'ammo-basic',
    name: 'Municao Basica',
    category: 'ammo',
    priceTier: 'cheap',
    priceEb: 10,
    priceNote: 'por 10',
    description: 'Municao padrao, sem efeitos especiais.',
  },
  {
    id: 'ammo-anti-armor',
    name: 'Municao Anti-Blindagem',
    category: 'ammo',
    priceTier: 'premium',
    priceEb: 100,
    priceNote: 'por 10',
    description: 'Reduz SP em 2 em vez de 1.',
  },
  {
    id: 'ammo-emp',
    name: 'Municao EMP',
    category: 'ammo',
    priceTier: 'expensive',
    priceEb: 500,
    priceNote: 'por 10 (granadas)',
    description: 'DV15 Cibertecnologia, desativa ciberware.',
  },
  {
    id: 'ammo-incendiary',
    name: 'Municao Incendiaria',
    category: 'ammo',
    priceTier: 'premium',
    priceEb: 100,
    priceNote: 'por 10',
    description: 'Alvo pega fogo ao atravessar armadura.',
  },
  {
    id: 'ammo-rubber',
    name: 'Municao Borracha',
    category: 'ammo',
    priceTier: 'cheap',
    priceEb: 10,
    priceNote: 'por 10',
    description: 'Nao causa lesoes criticas.',
  },
  {
    id: 'armor-leather',
    name: 'Armadura Couro',
    category: 'armor',
    priceTier: 'everyday',
    priceEb: 20,
    description: 'SP 4, sem penalidade.',
  },
  {
    id: 'armor-kevlar',
    name: 'Armadura Kevlar',
    category: 'armor',
    priceTier: 'costly',
    priceEb: 50,
    description: 'SP 7, sem penalidade.',
  },
  {
    id: 'armor-light',
    name: 'Blindagem Leve',
    category: 'armor',
    priceTier: 'premium',
    priceEb: 100,
    description: 'SP 11, sem penalidade.',
  },
  {
    id: 'armor-heavy',
    name: 'Blindagem Pesada',
    category: 'armor',
    priceTier: 'expensive',
    priceEb: 500,
    grid: { w: 3, h: 2 },
    description: 'SP 13, -2 REF/DEX/MOVE.',
  },
  {
    id: 'armor-metalgear',
    name: 'Metalgear',
    category: 'armor',
    priceTier: 'luxury',
    priceEb: 5000,
    grid: { w: 3, h: 3 },
    description: 'SP 18, -4 REF/DEX/MOVE.',
  },
  {
    id: 'ballistic-shield',
    name: 'Escudo Balistico',
    category: 'armor',
    priceTier: 'premium',
    priceEb: 100,
    description: 'Escudo SP 10 PV, ocupa 1 braco.',
  },
  {
    id: 'neural-link',
    name: 'Link Neural',
    category: 'cyberware',
    priceTier: 'expensive',
    priceEb: 500,
    source: 'clinica',
    description: 'Necessario para Neuralware. 5 slots de opcao.',
  },
  {
    id: 'kerenzikov',
    name: 'Kerenzikov',
    category: 'cyberware',
    priceTier: 'expensive',
    priceEb: 500,
    source: 'clinica',
    description: '+2 Iniciativa, ativo.',
  },
  {
    id: 'sandevistan',
    name: 'Sandevistan',
    category: 'cyberware',
    priceTier: 'expensive',
    priceEb: 500,
    source: 'clinica',
    description: '+3 Iniciativa por 1 minuto.',
  },
  {
    id: 'cybereye',
    name: 'Ciberolho',
    category: 'cyberware',
    priceTier: 'premium',
    priceEb: 100,
    source: 'clinica',
    description: 'Ciberolho com 3 slots de opcao.',
  },
  {
    id: 'cyberarm',
    name: 'Ciberbraco',
    category: 'cyberware',
    priceTier: 'expensive',
    priceEb: 500,
    source: 'hospital',
    description: 'Ciberbraco com 4 slots de opcao.',
  },
  {
    id: 'subdermal-armor',
    name: 'Armadura Subdermica',
    category: 'cyberware',
    priceTier: 'very-expensive',
    priceEb: 1000,
    source: 'hospital',
    description: 'Armadura SP11 no corpo e cabeca.',
  },
  {
    id: 'black-lace',
    name: 'Black Lace',
    category: 'drugs',
    priceTier: 'costly',
    priceEb: 50,
    description: 'Ignora Gravemente Ferido, risco de vicio.',
  },
  {
    id: 'smash',
    name: 'Smash',
    category: 'drugs',
    priceTier: 'cheap',
    priceEb: 10,
    description: '+2 em varias habilidades sociais e fisicas.',
  },
  {
    id: 'synthcoke',
    name: 'Synthcoke',
    category: 'drugs',
    priceTier: 'everyday',
    priceEb: 20,
    description: '+1 REF, risco de vicio.',
  },
  {
    id: 'cyber-install-shop',
    name: 'Instalacao de Cyberware (Loja)',
    category: 'services',
    priceTier: 'premium',
    priceEb: 100,
    priceNote: 'por instalacao',
    description: 'Instalacao de cyberware encontrado.',
  },
  {
    id: 'therapy',
    name: 'Terapia (Perda Padrao)',
    category: 'services',
    priceTier: 'expensive',
    priceEb: 500,
    priceNote: 'por tratamento',
    description: 'Recupera Humanidade (perda padrao).',
  },
  {
    id: 'trauma-team',
    name: 'Trauma Team (Plano Prata)',
    category: 'services',
    priceTier: 'expensive',
    priceEb: 500,
    priceNote: 'por mes',
    description: 'Plano mensal de emergencia.',
  },
  {
    id: 'hotel-night',
    name: 'Hotel (por noite)',
    category: 'services',
    priceTier: 'premium',
    priceEb: 100,
    priceNote: 'por noite',
    description: 'Hospedagem padrao.',
  },
  {
    id: 'cube-hotel',
    name: 'Cube Hotel',
    category: 'housing',
    priceTier: 'expensive',
    priceEb: 500,
    priceNote: 'por mes',
    description: 'Quarto sem janelas. Hospedagem minima.',
  },
  {
    id: 'studio-apartment',
    name: 'Apartamento Estudio',
    category: 'housing',
    priceTier: 'very-expensive',
    priceEb: 1500,
    priceNote: 'por mes',
    description: 'Apartamento compacto, comida decente.',
  },
  {
    id: 'luxury-conapt',
    name: 'Conapt de Luxo',
    category: 'housing',
    priceTier: 'luxury',
    priceEb: 7500,
    priceNote: 'por mes',
    description: 'Padrao corporativo de alto luxo.',
  },
  {
    id: 'luxury-penthouse',
    name: 'Cobertura de Luxo',
    category: 'housing',
    priceTier: 'super-luxury',
    priceEb: 15000,
    priceNote: 'por mes',
    description: 'Cobertura premium, vigilancia corporativa.',
  },
];
